Repository dnd-side-project/dnd-10th-2-backend, pull requests merged in 2024-02, with the labels that each got.

#10 [Feat/#3] Github Action을 활용한 ECR 이미지 업로드 및 ECS 배포 추가
  .github/workflows/deploy.yml
  task-definition.json
Labels: ✨ Type: Enhancement, 🟡 Priority: Medium, 🔛 Status: In Progress

#14 [Refactor#13] ERD에 맞게 코드 리팩토링
  src/main/java/org/dnd/modutimer/ModutimerApplication.java
  src/main/java/org/dnd/modutimer/common/domain/AuditableEntity.java
  src/main/java/org/dnd/modutimer/common/domain/BaseEntity.java
  src/main/java/org/dnd/modutimer/common/exception/ApiException.java
  src/main/java/org/dnd/modutimer/common/exception/BadGatewayError.java
  src/main/java/org/dnd/modutimer/common/exception/BadRequestError.java
  src/main/java/org/dnd/modutimer/common/exception/CustomErrorAttributes.java
  src/main/java/org/dnd/modutimer/common/exception/ForbiddenError.java
  src/main/java/org/dnd/modutimer/common/exception/GlobalExceptionHandler.java
  src/main/java/org/dnd/modutimer/common/exception/GlobalValidationHandler.java
  src/main/java/org/dnd/modutimer/common/exception/InternalServerError.java
  src/main/java/org/dnd/modutimer/common/exception/NotFoundError.java
  src/main/java/org/dnd/modutimer/common/exception/UnAuthorizedError.java
  src/main/java/org/dnd/modutimer/common/security/CustomAuthenticationEntryPoint.java
  src/main/java/org/dnd/modutimer/common/security/CustomUserDetailsService.java
  src/main/java/org/dnd/modutimer/common/security/JWTProvider.java
  src/main/java/org/dnd/modutimer/common/security/JwtAuthenticationFilter.java
  src/main/java/org/dnd/modutimer/common/utils/ApiUtils.java
  src/main/java/org/dnd/modutimer/common/utils/FilterResponseUtils.java
  src/main/java/org/dnd/modutimer/config/SecurityConfig.java
  src/main/java/org/dnd/modutimer/config/SwaggerConfig.java
  src/main/java/org/dnd/modutimer/timer/application/TimerService.java
  src/main/java/org/dnd/modutimer/timer/controller/TimerController.java
  src/main/java/org/dnd/modutimer/timer/domain/Duration.java
  src/main/java/org/dnd/modutimer/timer/domain/Timer.java
  src/main/java/org/dnd/modutimer/timer/dto/TimerCreateRequest.java
  src/main/java/org/dnd/modutimer/timer/dto/TimerInfoResponse.java
  src/main/java/org/dnd/modutimer/user/application/UserFindService.java
  src/main/java/org/dnd/modutimer/user/application/UserService.java
  src/main/java/org/dnd/modutimer/user/controller/UserController.java
  src/main/java/org/dnd/modutimer/user/domain/User.java
  src/main/java/org/dnd/modutimer/user/domain/UserRepository.java
  src/main/java/org/dnd/modutimer/user/dto/EmailCheckRequest.java
  src/main/java/org/dnd/modutimer/user/dto/UpdatePasswordRequest.java
  src/main/java/org/dnd/modutimer/user/dto/UserInfoResponse.java
  src/main/java/org/dnd/modutimer/user/dto/UserLoginRequest.java
  src/main/java/org/dnd/modutimer/user/dto/UserLoginResponse.java
  src/main/java/org/dnd/modutimer/user/dto/UserRegisterRequest.java
  src/test/java/org/dnd/modutimer/ModutimerApplicationTests.java
Labels: ✨ Type: Enhancement, 🟡 Priority: Medium, 🔛 Status: In Progress, 🔧 Type: Maintenance

#18 [Feat/#7] Github actions workflow에 checkstyle 단계 추가
  .github/workflows/build.yml
  build.gradle
  config/checkstyle-config.xml
Labels: ✨ Type: Enhancement, 🟡 Priority: Medium, 🔛 Status: In Progress

#20 [Feat#19] 회의 생성 및 id 기반 조회 기능 구현
  src/main/java/org/dnd/timeet/config/SecurityConfig.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingService.java
  src/main/java/org/dnd/timeet/meeting/controller/MeetingController.java
  src/main/java/org/dnd/timeet/meeting/domain/Meeting.java
  src/main/java/org/dnd/timeet/meeting/domain/MeetingRepository.java
  src/main/java/org/dnd/timeet/meeting/domain/MeetingStatus.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingCreateRequest.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingCreateResponse.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingInfoResponse.java
  src/main/java/org/dnd/timeet/timer/application/TimerService.java
  src/main/java/org/dnd/timeet/timer/controller/TimerController.java
  src/main/java/org/dnd/timeet/timer/domain/Timer.java
  src/main/java/org/dnd/timeet/timer/domain/TimerDuration.java
  src/main/java/org/dnd/timeet/timer/dto/TimerCreateRequest.java
  src/main/java/org/dnd/timeet/timer/dto/TimerInfoResponse.java
Labels: 🚩 Priority: High, 🟡 Priority: Medium, ✅ Status: Done

#25 [Feat/#13] ERD 코드 반영 및 안건 관리 기능 추가
  build.gradle
  src/main/java/org/dnd/timeet/agenda/application/AgendaService.java
  src/main/java/org/dnd/timeet/agenda/controller/AgendaController.java
  src/main/java/org/dnd/timeet/agenda/domain/Agenda.java
  src/main/java/org/dnd/timeet/agenda/domain/AgendaRepository.java
  src/main/java/org/dnd/timeet/agenda/domain/AgendaStatus.java
  src/main/java/org/dnd/timeet/agenda/domain/AgendaType.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaActionRequest.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaActionResponse.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaCreateRequest.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaInfoResponse.java
  src/main/java/org/dnd/timeet/common/exception/GlobalExceptionHandler.java
  src/main/java/org/dnd/timeet/config/SecurityConfig.java
  src/main/java/org/dnd/timeet/config/WebSocketConfig.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingService.java
  src/main/java/org/dnd/timeet/meeting/controller/MeetingController.java
  src/main/java/org/dnd/timeet/meeting/domain/Meeting.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingCreateRequest.java
  src/main/java/org/dnd/timeet/member/controller/MemberController.java
  src/main/java/org/dnd/timeet/member/domain/Member.java
  src/main/java/org/dnd/timeet/participant/domain/Participant.java
  src/main/java/org/dnd/timeet/participant/domain/ParticipantRepository.java
  src/main/java/org/dnd/timeet/timer/domain/Timer.java
Labels: ✨ Type: Enhancement, 🟡 Priority: Medium, 🔛 Status: In Progress

#29 [Feat#28] 회의 참여자 조회 기능 개발
  src/main/java/org/dnd/timeet/meeting/application/MeetingService.java
  src/main/java/org/dnd/timeet/meeting/controller/MeetingController.java
  src/main/java/org/dnd/timeet/meeting/domain/MeetingRepository.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingInfoResponse.java
  src/main/java/org/dnd/timeet/member/dto/MemberInfoListResponse.java
  src/main/java/org/dnd/timeet/member/dto/MemberInfoResponse.java
Labels: ✨ Type: Enhancement, 🟡 Priority: Medium, 🔛 Status: In Progress

#31 [Feat#27] 회의 삭제 기능 추가
  src/main/java/org/dnd/timeet/meeting/application/MeetingService.java
  src/main/java/org/dnd/timeet/meeting/controller/MeetingController.java
Labels: ✨ Type: Enhancement, 🟢 Priority: Low, 🔛 Status: In Progress

#34 [Feat/#24] 안건 실시간 제어 및 갱신 API 개선
  src/main/java/org/dnd/timeet/agenda/application/AgendaService.java
  src/main/java/org/dnd/timeet/agenda/controller/AgendaController.java
  src/main/java/org/dnd/timeet/agenda/domain/Agenda.java
  src/main/java/org/dnd/timeet/agenda/domain/AgendaAction.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaActionResponse.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaCreateRequest.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaInfoResponse.java
  src/main/java/org/dnd/timeet/common/utils/DateTimeUtils.java
  src/main/java/org/dnd/timeet/common/utils/DurationUtils.java
  src/main/java/org/dnd/timeet/config/WebSocketConfig.java
  src/test/java/org/dnd/timeet/TimeetApplicationTests.java
  src/test/java/org/dnd/timeet/common/utils/DurationUtilsTest.java
Labels: ✨ Type: Enhancement, 🟡 Priority: Medium, 🔛 Status: In Progress

#30 [Feat#26] 회의 리포트 생성 및 회의 종료 기능을 추가
  src/main/java/org/dnd/timeet/agenda/dto/AgendaReportInfoResponse.java
  src/main/java/org/dnd/timeet/common/utils/TimeUtils.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingService.java
  src/main/java/org/dnd/timeet/meeting/controller/MeetingController.java
  src/main/java/org/dnd/timeet/meeting/domain/Meeting.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingReportInfoResponse.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingReportResponse.java
Labels: 🟡 Priority: Medium

#40 [Feat/#35] 스케줄링을 통한 자동 회의 시작 기능 구현 및 남은 시간 조회 기능 구현
  src/main/java/org/dnd/timeet/agenda/dto/AgendaReportInfoResponse.java
  src/main/java/org/dnd/timeet/common/utils/DurationUtils.java
  src/main/java/org/dnd/timeet/common/utils/TimeUtils.java
  src/main/java/org/dnd/timeet/config/AsyncConfig.java
  src/main/java/org/dnd/timeet/config/SchedulerConfig.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingAsyncService.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingScheduler.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingService.java
  src/main/java/org/dnd/timeet/meeting/controller/MeetingController.java
  src/main/java/org/dnd/timeet/meeting/domain/Meeting.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingCreateRequest.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingInfoResponse.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingRemainingTimeResponse.java
Labels: ✨ Type: Enhancement, 🟡 Priority: Medium, 🔛 Status: In Progress

#23 [Feat#22] FCM을 활용한 알림 시스템 구현
  .github/workflows/build.yml
  .gitignore
  build.gradle
  src/main/java/org/dnd/timeet/common/security/annotation/ReqUser.java
  src/main/java/org/dnd/timeet/config/FCMConfig.java
  src/main/java/org/dnd/timeet/fcm/application/FCMNotificationService.java
  src/main/java/org/dnd/timeet/fcm/domain/FCMNotificationRequestDto.java
  src/main/java/org/dnd/timeet/member/application/MemberService.java
  src/main/java/org/dnd/timeet/member/controller/MemberController.java
  src/main/java/org/dnd/timeet/member/domain/Member.java
  src/main/java/org/dnd/timeet/member/dto/RegisterFcmRequest.java
Labels: ✨ Type: Enhancement, 🟡 Priority: Medium, 🆕 Status: Available

#41 [Feat#38] Github Action 및 docker compose를 활용한 배포 파이프라인 구현
  .github/workflows/build-deploy.yml
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  Dockerfile
  src/main/resources/application.yml
Labels: 🟡 Priority: Medium

#43 [Feat#38] Github Action workflow 분리 및 mysql db production 적용
  .github/workflows/build-deploy.yml
  .github/workflows/check.yml
  .gitignore
  docker-compose.yml
Labels: 🟡 Priority: Medium

#45 [Feat/#36] 닉네임 추가 기능을 개발한다.
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  src/main/java/org/dnd/timeet/config/SecurityConfig.java
  src/main/java/org/dnd/timeet/member/application/MemberService.java
  src/main/java/org/dnd/timeet/member/controller/MemberController.java
  src/main/java/org/dnd/timeet/member/domain/Member.java
  src/main/java/org/dnd/timeet/member/dto/MemberNicknameRequest.java
Labels: 🐛 Type: Bug, ✨ Type: Enhancement, 🟡 Priority: Medium, 🔛 Status: In Progress

#46 [Feat/#37] 웹소켓 연결에 JWT 기반 인증을 적용한다.
  src/main/java/org/dnd/timeet/common/interceptor/JwtChannelInterceptor.java
  src/main/java/org/dnd/timeet/common/security/JwtAuthenticationFilter.java
  src/main/java/org/dnd/timeet/common/security/JwtProvider.java
  src/main/java/org/dnd/timeet/config/SecurityConfig.java
  src/main/java/org/dnd/timeet/config/WebSocketConfig.java
  src/main/java/org/dnd/timeet/meeting/application/WebSocketSessionManager.java
  src/main/java/org/dnd/timeet/oauth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: ✨ Type: Enhancement, 🚩 Priority: High, 🔛 Status: In Progress

#47 dev -> main
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  src/main/java/org/dnd/timeet/common/interceptor/JwtChannelInterceptor.java
  src/main/java/org/dnd/timeet/common/security/JwtAuthenticationFilter.java
  src/main/java/org/dnd/timeet/common/security/JwtProvider.java
  src/main/java/org/dnd/timeet/config/SecurityConfig.java
  src/main/java/org/dnd/timeet/config/WebSocketConfig.java
  src/main/java/org/dnd/timeet/meeting/application/WebSocketSessionManager.java
  src/main/java/org/dnd/timeet/member/application/MemberService.java
  src/main/java/org/dnd/timeet/member/controller/MemberController.java
  src/main/java/org/dnd/timeet/member/domain/Member.java
  src/main/java/org/dnd/timeet/member/dto/MemberNicknameRequest.java
  src/main/java/org/dnd/timeet/oauth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: 🐛 Type: Bug, ✨ Type: Enhancement, 🚩 Priority: High, ✅ Status: Done

#49 [Feat#48] Production을 위한 Oauth2 redirect-uri 로직 수정
  .github/pull_request_template.md
  src/main/java/org/dnd/timeet/oauth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: 🟡 Priority: Medium

#52 [#50] feat: 멤버 정보 조회 API 추가
  src/main/java/org/dnd/timeet/member/controller/MemberController.java
  src/main/java/org/dnd/timeet/member/dto/MemberInfoResponse.java
Labels: 🟡 Priority: Medium

#54 [Feat/#50] 회의 종료시 안건 상태 관리 및 권한 확인 작업 추가
  src/main/java/org/dnd/timeet/agenda/application/AgendaService.java
  src/main/java/org/dnd/timeet/agenda/domain/Agenda.java
  src/main/java/org/dnd/timeet/common/exception/ForbiddenError.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingService.java
  src/main/java/org/dnd/timeet/meeting/controller/MeetingController.java
Labels: ✨ Type: Enhancement, 🚩 Priority: High, 🔛 Status: In Progress

#56 [Feat/#55] 회의 시간 자동 종료 기능 및 안건 시간 총합으로 회의 시간 설정 구현
  src/main/java/org/dnd/timeet/agenda/application/AgendaService.java
  src/main/java/org/dnd/timeet/agenda/controller/AgendaController.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaCreateRequest.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaInfoResponse.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingAsyncService.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingScheduler.java
  src/main/java/org/dnd/timeet/meeting/controller/MeetingController.java
  src/main/java/org/dnd/timeet/meeting/domain/Meeting.java
  src/main/java/org/dnd/timeet/meeting/domain/MeetingRepository.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingInfoResponse.java
Labels: ✨ Type: Enhancement, 🚩 Priority: High, 🔛 Status: In Progress

#57 dev -> main
  .github/pull_request_template.md
  src/main/java/org/dnd/timeet/agenda/application/AgendaService.java
  src/main/java/org/dnd/timeet/agenda/controller/AgendaController.java
  src/main/java/org/dnd/timeet/agenda/domain/Agenda.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaCreateRequest.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaInfoResponse.java
  src/main/java/org/dnd/timeet/common/exception/ForbiddenError.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingAsyncService.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingScheduler.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingService.java
  src/main/java/org/dnd/timeet/meeting/controller/MeetingController.java
  src/main/java/org/dnd/timeet/meeting/domain/Meeting.java
  src/main/java/org/dnd/timeet/meeting/domain/MeetingRepository.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingInfoResponse.java
  src/main/java/org/dnd/timeet/member/controller/MemberController.java
  src/main/java/org/dnd/timeet/member/dto/MemberInfoResponse.java
  src/main/java/org/dnd/timeet/oauth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: 🐛 Type: Bug, ✨ Type: Enhancement, 🚩 Priority: High, 🔛 Status: In Progress

#63 [Feat/#59] 회의실 나가기 기능 및 안건 수정 기능 개발, 기획 변경으로 인한 코드 수정
  src/main/java/org/dnd/timeet/agenda/application/AgendaService.java
  src/main/java/org/dnd/timeet/agenda/controller/AgendaController.java
  src/main/java/org/dnd/timeet/agenda/domain/Agenda.java
  src/main/java/org/dnd/timeet/agenda/domain/AgendaRepository.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaActionResponse.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaCreateRequest.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaPatchRequest.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaPatchResponse.java
  src/main/java/org/dnd/timeet/common/utils/DurationUtils.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingAsyncService.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingScheduler.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingService.java
  src/main/java/org/dnd/timeet/meeting/controller/MeetingController.java
  src/main/java/org/dnd/timeet/meeting/domain/Meeting.java
  src/main/java/org/dnd/timeet/meeting/domain/MeetingRepository.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingInfoResponse.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingMemberInfoResponse.java
  src/main/java/org/dnd/timeet/participant/domain/Participant.java
  src/main/java/org/dnd/timeet/participant/domain/ParticipantRepository.java
Labels: ✨ Type: Enhancement, 🚩 Priority: High, 🔛 Status: In Progress

#64 [#62] feat: Add google oauth2 Login
  src/main/java/org/dnd/timeet/member/domain/Member.java
  src/main/java/org/dnd/timeet/member/domain/MemberRepository.java
  src/main/java/org/dnd/timeet/oauth/info/OAuth2UserInfo.java
  src/main/java/org/dnd/timeet/oauth/info/OAuth2UserInfoFactory.java
  src/main/java/org/dnd/timeet/oauth/info/impl/GoogleOAuth2UserInfo.java
  src/main/java/org/dnd/timeet/oauth/info/impl/KakaoOAuth2UserInfo.java
Labels: ✨ Type: Enhancement, 🟡 Priority: Medium, 🔛 Status: In Progress

#66 [Feat#65] 안건 순서 수정 기능 개발
  src/main/java/org/dnd/timeet/agenda/application/AgendaService.java
  src/main/java/org/dnd/timeet/agenda/controller/AgendaController.java
  src/main/java/org/dnd/timeet/agenda/domain/Agenda.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaActionResponse.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaOrderRequest.java
Labels: ✨ Type: Enhancement, 🟡 Priority: Medium, 🔛 Status: In Progress

#67 [Feat/#-] 기획 사항을 고려하여 기능 구현 및 리팩토링
  src/main/java/org/dnd/timeet/agenda/application/AgendaService.java
  src/main/java/org/dnd/timeet/agenda/domain/Agenda.java
  src/main/java/org/dnd/timeet/agenda/domain/AgendaAction.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaActionRequest.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaInfoResponse.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaReportInfoResponse.java
  src/main/java/org/dnd/timeet/common/utils/TimeUtils.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingService.java
  src/main/java/org/dnd/timeet/meeting/controller/MeetingController.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingCreateRequest.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingCurrentDurationResponse.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingInfoResponse.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingMemberInfoResponse.java
  src/main/java/org/dnd/timeet/member/domain/Member.java
Labels: ✨ Type: Enhancement, 🚩 Priority: High, 🔛 Status: In Progress

#68 dev -> main
  docker-compose.yml
  src/main/java/org/dnd/timeet/agenda/application/AgendaService.java
  src/main/java/org/dnd/timeet/agenda/controller/AgendaController.java
  src/main/java/org/dnd/timeet/agenda/domain/Agenda.java
  src/main/java/org/dnd/timeet/agenda/domain/AgendaAction.java
  src/main/java/org/dnd/timeet/agenda/domain/AgendaRepository.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaActionRequest.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaActionResponse.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaCreateRequest.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaInfoResponse.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaOrderRequest.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaPatchRequest.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaPatchResponse.java
  src/main/java/org/dnd/timeet/agenda/dto/AgendaReportInfoResponse.java
  src/main/java/org/dnd/timeet/common/utils/DurationUtils.java
  src/main/java/org/dnd/timeet/common/utils/TimeUtils.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingAsyncService.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingScheduler.java
  src/main/java/org/dnd/timeet/meeting/application/MeetingService.java
  src/main/java/org/dnd/timeet/meeting/controller/MeetingController.java
  src/main/java/org/dnd/timeet/meeting/domain/Meeting.java
  src/main/java/org/dnd/timeet/meeting/domain/MeetingRepository.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingCreateRequest.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingCurrentDurationResponse.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingInfoResponse.java
  src/main/java/org/dnd/timeet/meeting/dto/MeetingMemberInfoResponse.java
  src/main/java/org/dnd/timeet/member/domain/Member.java
  src/main/java/org/dnd/timeet/member/domain/MemberRepository.java
  src/main/java/org/dnd/timeet/oauth/info/OAuth2UserInfo.java
  src/main/java/org/dnd/timeet/oauth/info/OAuth2UserInfoFactory.java
  src/main/java/org/dnd/timeet/oauth/info/impl/GoogleOAuth2UserInfo.java
  src/main/java/org/dnd/timeet/oauth/info/impl/KakaoOAuth2UserInfo.java
  src/main/java/org/dnd/timeet/participant/domain/Participant.java
  src/main/java/org/dnd/timeet/participant/domain/ParticipantRepository.java
Labels: 🐛 Type: Bug, ✨ Type: Enhancement, 🚩 Priority: High, ✅ Status: Done

#69 [Feat#-] Chore imageNum 초기화 수정 및 redirect-uri 정책 변경
  src/main/java/org/dnd/timeet/oauth/application/CustomOAuth2UserService.java
  src/main/java/org/dnd/timeet/oauth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: ✨ Type: Enhancement, 🟡 Priority: Medium, 🔛 Status: In Progress

#70 dev -> main
  src/main/java/org/dnd/timeet/oauth/application/CustomOAuth2UserService.java
  src/main/java/org/dnd/timeet/oauth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: 🚩 Priority: High

#71 [Fix/#-] CORS 에러 수정을 위해 allowed origin 추가
  src/main/java/org/dnd/timeet/config/SecurityConfig.java
Labels: 🐛 Type: Bug, 🚩 Priority: High

#74 [Feat/#73] 회의 관리 기능에 대한 통합 테스트 코드 구현
  build.gradle
  src/main/java/org/dnd/timeet/meeting/dto/MeetingCreateRequest.java
  src/test/java/org/dnd/timeet/common/security/annotation/WithMockCustomUser.java
  src/test/java/org/dnd/timeet/common/security/annotation/WithMockCustomUserSecurityContextFactory.java
  src/test/java/org/dnd/timeet/meeting/integration/MeetingIntegrationTest.java
Labels: ✨ Type: Enhancement, 🟡 Priority: Medium, 🔛 Status: In Progress, 🔧 Type: Maintenance
